ekf_filter_node:
  ros__parameters:
    # 기본
    frequency: 50.0
    sensor_timeout: 0.2
    two_d_mode: true
    publish_tf: true              # EKF가 odom->base_link TF를 퍼블리시
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # === 입력 1: 네 노드가 퍼블리시하는 오도메트리 ===
    #   /odom 은 엔코더+IMU 융합 추정(네 코드) 값
    odom0: /odom
    odom0_queue_size: 5
    odom0_differential: false
    odom0_relative: false
    # x, y, z, roll, pitch, yaw,  vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    odom0_config: [ true, true, false,
                    false, false, true,
                    true, false, false,
                    false, false, true,
                    false, false, false ]

    # === 입력 2: IMU ===
    imu0: /imu/data
    imu0_queue_size: 20
    imu0_differential: false
    imu0_relative: false
    # x, y, z, roll, pitch, yaw,  vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    imu0_config:  [ false, false, false,
                    false, false, true,    # orientation yaw 사용
                    false, false, false,
                    false, false, true,    # gyro z 사용
                    true,  true,  true ]   # 가속도 (원하면 false로 꺼도 됨)

    imu0_remove_gravitational_acceleration: true


